
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class ColorChooseJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ColorChooseJFrame
     */
    public ColorChooseJFrame() {
        initComponents();
        lbDisplay.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbDisplay = new javax.swing.JLabel();
        red = new javax.swing.JRadioButton();
        blue = new javax.swing.JRadioButton();
        green = new javax.swing.JRadioButton();
        black = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(red);
        red.setText("Red");
        red.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                redStateChanged(evt);
            }
        });

        buttonGroup1.add(blue);
        blue.setText("Blue");
        blue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                blueStateChanged(evt);
            }
        });

        buttonGroup1.add(green);
        green.setText("Green");
        green.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                greenStateChanged(evt);
            }
        });

        buttonGroup1.add(black);
        black.setText("Black");
        black.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                blackStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(green)
                    .addComponent(blue)
                    .addComponent(red)
                    .addComponent(black, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(red)
                .addGap(18, 18, 18)
                .addComponent(blue)
                .addGap(18, 18, 18)
                .addComponent(green)
                .addGap(18, 18, 18)
                .addComponent(black)
                .addGap(18, 18, 18)
                .addComponent(lbDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_redStateChanged
        // TODO add your handling code here:
        if(red.isSelected()){
            lbDisplay.setText("Red is selected");
            lbDisplay.setBackground(Color.RED);
            lbDisplay.setForeground(Color.white);
        }
    }//GEN-LAST:event_redStateChanged

    private void blueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_blueStateChanged
        // TODO add your handling code here:
        if(blue.isSelected()){
            lbDisplay.setText("Blue is selected");
            lbDisplay.setBackground(Color.BLUE);
            lbDisplay.setForeground(Color.white);
        }
    }//GEN-LAST:event_blueStateChanged

    private void greenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_greenStateChanged
        // TODO add your handling code here:
        if(green.isSelected()){
            lbDisplay.setText("Green is selected");
            lbDisplay.setBackground(Color.GREEN);
            lbDisplay.setForeground(Color.white);
        }
    }//GEN-LAST:event_greenStateChanged

    private void blackStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_blackStateChanged
        // TODO add your handling code here:
        if(black.isSelected()){
            lbDisplay.setText("Black is selected");
            lbDisplay.setBackground(Color.BLACK);
            lbDisplay.setForeground(Color.white);
        }
    }//GEN-LAST:event_blackStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorChooseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorChooseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorChooseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorChooseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorChooseJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton black;
    private javax.swing.JRadioButton blue;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton green;
    private javax.swing.JLabel lbDisplay;
    private javax.swing.JRadioButton red;
    // End of variables declaration//GEN-END:variables
}
