
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class FlagJFrame extends javax.swing.JFrame {

    /**
     * Creates new form FlagJFrame
     */
    ImageIcon iconVietnam = new ImageIcon("vietnam.png");
    ImageIcon iconChina = new ImageIcon("china.png");
    ImageIcon iconUSA = new ImageIcon("usa.png");
    public FlagJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDisplay = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnChoose = new javax.swing.JMenu();
        mnVietnam = new javax.swing.JMenuItem();
        mnChina = new javax.swing.JMenuItem();
        mnUSA = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnChoose.setText("Choose flag");

        mnVietnam.setText("Vietnam");
        mnVietnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVietnamActionPerformed(evt);
            }
        });
        mnChoose.add(mnVietnam);

        mnChina.setText("China");
        mnChina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChinaActionPerformed(evt);
            }
        });
        mnChoose.add(mnChina);

        mnUSA.setText("USA");
        mnUSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUSAActionPerformed(evt);
            }
        });
        mnChoose.add(mnUSA);

        jMenuBar1.add(mnChoose);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnUSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUSAActionPerformed
        // TODO add your handling code here:
        Image img = iconUSA.getImage();
        img =img.getScaledInstance(lbDisplay.getWidth(), lbDisplay.getHeight(), Image.SCALE_SMOOTH);
        iconUSA = new ImageIcon(img);
        lbDisplay.setIcon(iconUSA);
    }//GEN-LAST:event_mnUSAActionPerformed

    private void mnVietnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVietnamActionPerformed
        // TODO add your handling code here:
        Image img = iconVietnam.getImage();
        img =img.getScaledInstance(lbDisplay.getWidth(), lbDisplay.getHeight(), Image.SCALE_SMOOTH);
        iconVietnam = new ImageIcon(img);
        lbDisplay.setIcon(iconVietnam);
    }//GEN-LAST:event_mnVietnamActionPerformed

    private void mnChinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChinaActionPerformed
        // TODO add your handling code here:
        Image img = iconChina.getImage();
        img =img.getScaledInstance(lbDisplay.getWidth(), lbDisplay.getHeight(), Image.SCALE_SMOOTH);
        iconChina = new ImageIcon(img);
        lbDisplay.setIcon(iconChina);
    }//GEN-LAST:event_mnChinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlagJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlagJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlagJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlagJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlagJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbDisplay;
    private javax.swing.JMenuItem mnChina;
    private javax.swing.JMenu mnChoose;
    private javax.swing.JMenuItem mnUSA;
    private javax.swing.JMenuItem mnVietnam;
    // End of variables declaration//GEN-END:variables
}
