
import java.awt.Image;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class ComboBoxDemo extends javax.swing.JFrame {

    /**
     * Creates new form ComboBoxDemo
     */
    ImageIcon iconBird = new ImageIcon("bird.png");
    ImageIcon iconCat = new ImageIcon("cat.png");
    ImageIcon iconDog = new ImageIcon("dog.png");
    ImageIcon iconRabbit = new ImageIcon("rabbit.png");
    ImageIcon iconPig = new ImageIcon("pig.png");
    public ComboBoxDemo() {
        initComponents();
        setTitle("ComboBox Demo");
        jLabel1.setIcon(iconBird);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxDemo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxDemo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxDemo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bird", "Cat", "Dog", "Rabbit", "Pig" }));
        jComboBoxDemo.setSelectedItem("bird.png");
        jComboBoxDemo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDemoItemStateChanged(evt);
            }
        });
        jComboBoxDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDemoActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jComboBoxDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jComboBoxDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDemoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDemoItemStateChanged
        // TODO add your handling code here:
          String select = (String) jComboBoxDemo.getSelectedItem();
        if (select.equals("Bird")) {
            jLabel1.setIcon(iconBird);
        }
        if (select.equals("Cat")) {
            jLabel1.setIcon(iconCat);
        }
        if (select.equals("Dog")) {
            jLabel1.setIcon(iconDog);
        }
        if (select.equals("Rabbit")) {
            jLabel1.setIcon(iconRabbit);
        }
        if (select.equals("Pig")) {
            jLabel1.setIcon(iconPig);
        }
    }//GEN-LAST:event_jComboBoxDemoItemStateChanged

    private void jComboBoxDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDemoActionPerformed
     /*   // TODO add your handling code here:       
        String s = (String) jComboBoxDemo.getSelectedItem();
        ImageIcon ic = new ImageIcon(s);
        Image img = ic.getImage();
        img =img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ic = new ImageIcon(img);
        jLabel1.setIcon(ic);*/
    }//GEN-LAST:event_jComboBoxDemoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboBoxDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboBoxDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboBoxDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboBoxDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboBoxDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxDemo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

/*    private void loadImages() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBoxDemo.getModel();
        model.setSelectedItem("bird.png");
        model.addElement("bird.png");
        model.addElement("dog.png");
        model.addElement("rabbit.png");
        model.addElement("pig.png");
        model.addElement("cat.png");
    }*/       
}
